const ITEMS = [
  {
    id: 1,
    name: "Fresh Sukumas",
    url: "https://i1.wp.com/www.aboutfresh.org/wp-content/uploads/2021/05/Kale.jpg?w=1920&ssl=1",
    price: "Ksh20",
    rating: "✩✩✩✩✩",
    category: "Vegetables",
    amount: 1,
  },
  {
    id: 2,
    name: "Red Apples",
    url: "https://images.heb.com/is/image/HEBGrocery/000375146",
    price: "Ksh40",
    rating: "✩✩✩✩✩",
    category: "Fruits",
  },
  {
    id: 3,
    name: "Cauliflowers",
    url: "https://kiasumart.com/wp-content/uploads/2020/09/Cauliflower-1Kg.jpeg",
    price: "Ksh100",
    rating: "✩✩✩✩✩",
    category: "Vegetables",
  },
  {
    id: 4,
    name: "Tomatoes",
    url: "http://demo.themepiko.com/stock/organic/wp-content/uploads/2019/06/product-2.jpg",
    price: "Ksh5",
    rating: "✩✩✩✩✩",
    category: "Fruits",
  },
  {
    id: 5,
    name: "Broccoli",
    url: "https://cdn0.woolworths.media/content/wowproductimages/large/134681.jpg",
    price: "Ksh70",
    rating: "✩✩✩✩✩",
    category: "Vegetables",
  },
  {
    id: 6,
    name: "Hoho",
    url: "https://zonefresh.com.au/wp-content/uploads/yellow-capsicum.jpg",
    price: "Ksh10",
    rating: "✩✩✩✩✩",
    category: "Vegetables",
  },
  {
    id: 7,
    name: "Milk",
    url: "https://cdnprod.mafretailproxy.com/sys-master-root/h9c/h67/27011375136798/159872_main.jpg_480Wx480H",
    price: "Ksh60/L",
    rating: "✩✩✩✩✩",
    category: "Animal Products",
  },
  {
    id: 8,
    name: "Beefmeat",
    url: "http://onedaycart.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/e/beef_3.jpg",
    price: "Ksh600/Kg",
    rating: "✩✩✩✩✩",
    category: "Animal Products",
  },
  {
    id: 9,
    name: "Lettuce",
    url: "https://cdn.britannica.com/77/170677-050-F7333D51/lettuce.jpg",
    price: "Ksh120",
    rating: "✩✩✩✩✩",
    category: "Vegetables",
  },
  {
    id: 10,
    name: "Cellery",
    url: "http://www.goodwholefood.com/wp-content/uploads/2016/03/Celery.jpg",
    price: "Ksh200",
    rating: "✩✩✩✩✩",
  },
  {
    id: 11,
    name: "Papaya",
    url: "https://healthjade.com/wp-content/uploads/2017/12/Papaya.jpg",
    price: "Ksh80",
    rating: "✩✩✩✩✩",
    category: "Fruits",
  },
  {
    id: 12,
    name: "Dragon Fruit",
    url: "https://www.specialtyproduce.com/sppics/9461.png",
    price: "Ksh80",
    rating: "✩✩✩✩✩",
    category: "Fruits",
  },
  {
    id: 13,
    name: "Mango",
    url: "https://media.millichronicle.com/2019/05/12125624/mangoes-chopped-and-fresh.jpg",
    price: "Ksh40",
    rating: "✩✩✩✩✩",
    category: "Fruits",
  },
  {
    id: 14,
    name: "Berries",
    url: "https://freepngimg.com/thumb/berries/29022-4-berries-transparent-image.png",
    price: "Ksh40",
    rating: "✩✩✩✩✩",
    category: "Fruits",
  },
];

export default ITEMS;
